Vagrant.configure(2) do |config|      
    config.vm.define "serviceInstanz2" do |conf|
      
      conf.vm.box = "debian/jessie64"
      conf.vm.network "private_network", ip: "192.168.0.106"

      conf.vm.provision "shell", inline: <<-SHELL
        echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list
        echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
        sudo apt-get update
        echo debconf shared/accepted-oracle-license-v1-1 select true | \
        sudo debconf-set-selections
        echo debconf shared/accepted-oracle-license-v1-1 seen true | \
        sudo debconf-set-selections
        sudo apt-get install -y oracle-java8-installer
        sudo apt-get install -y unzip
        wget https://releases.hashicorp.com/consul/0.7.0/consul_0.7.0_linux_amd64.zip
        unzip consul_0.7.0_linux_amd64.zip
        chmod +x consul
        mv consul /usr/bin/consul
      SHELL

      conf.vm.provision "shell", run: "always", inline: <<-SHELL
        java -jar /vagrant/target/MicroFilmprogrammService-0.0.1-SNAPSHOT-onejar.jar 50000 &
        consul agent -data-dir consul-data -join 192.168.0.5 -bind 192.168.0.106 
      SHELL
    end
  end